server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.200:1111
      #server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'